### PR TITLE
Added grammar for  Do while loop in java2cpp.y.

### PR DESCRIPTION
**Pull request by Shree-Gillorkar**

### CODE REVIEW

**Review by martinezlucas98 — CHANGES_REQUESTED** [review]
Here are some small changes you should make for it to work.

**Comment by Shree-Gillorkar** [comment]
@martinezlucas98, Thank you for your assistance. I made the changes as you suggested. I request you to review the code once more & let me know if any further changes are required.

**Comment by martinezlucas98** [comment]
Hey @Shree-Gillorkar I just fixed a typo you had, with that said, everything works fine so I will merge it to our branch.
I would recommend you to ```git pull``` to have everything up to date.
Thank you very much for your help in this project!! :100: :+1:

**Comment by Shree-Gillorkar** [comment]
I have successfully fetched upstream and updated repository from master
branch. Thank you! 😊

**Pull request merged**
